-- STUB / PRODUCCIÓN:
-- Este archivo se deja intencionalmente sin SQL ejecutable.
-- Motivo: era un TEMPLATE con placeholders ([...]) y rompía el autoload.
-- Template real: ../templates/arena_s3_vendors_cleanup.sql.template
