-- STUB / PRODUCCIÓN:
-- Este archivo se deja intencionalmente sin SQL ejecutable.
-- Motivo: era un TEMPLATE con placeholders ([...]) y rompía el autoload.
-- Template real: ../templates/transition_tbc_to_wotlk_vendors.sql.template
